Ferlab-Ste-Justine/clin-variant-etl

src/main/scala/bio/ferlab/clin/etl/CreateGenesTable.scala
https://github.com/Ferlab-Ste-Justine/clin-project/issues/634
=> feat#634 add field inheritance in genes tables from orphanet

.gitignore, build.sbt, src/main/scala/bio/ferlab/clin/etl/ByLocus.scala, src/main/scala/bio/ferlab/clin/etl/Consequences.scala, src/main/scala/bio/ferlab/clin/etl/CreateGenesTable.scala, src/main/scala/bio/ferlab/clin/etl/ImportVcf.scala, src/main/scala/bio/ferlab/clin/etl/Occurrences.scala, src/main/scala/bio/ferlab/clin/etl/PrepareIndex.scala, src/main/scala/bio/ferlab/clin/etl/etl.scala
https://github.com/Ferlab-Ste-Justine/clin-project/issues/624
=> feat#624: added hardcoded column variant_type with value germline

src/main/scala/bio/ferlab/clin/etl/CreatePublicTables.scala
https://github.com/Ferlab-Ste-Justine/clin-project/issues/636
=> Added create table statement for annovar and cancerhotspots

.github/workflows/deploy_minio.yml, src/main/resources/config/prod.conf, src/main/resources/config/qa.conf, src/main/resources/config/staging.conf, src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala
Validate secrets (probably have change)
```
MINIO_CLIN_QA_AWS_ENDPOINT
MINIO_CLIN_QA_AWS_ACCESS_KEY_ID
MINIO_CLIN_QA_AWS_SECRET_ACCESS_KEY
```
=> feat: CLIN-842 - rename buckets

src/main/resources/config/prod.conf, src/main/resources/config/qa.conf, src/main/resources/config/staging.conf, src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala, src/main/scala/bio/ferlab/clin/etl/varsome/Varsome.scala, src/test/resources/config/test.conf, src/test/resources/varsome_minimal.json, src/test/scala/bio/ferlab/clin/etl/varsome/VarsomeSpec.scala
**Tests on staging**
https://notebook.staging.cqgc.hsj.rtss.qc.ca/#/notebook/2H1BMJADA
=> feat: CLIN-925 - varsome filter with panels

src/main/scala/bio/ferlab/clin/etl/enriched/RunEnriched.scala, src/main/scala/bio/ferlab/clin/etl/enriched/Variants.scala, src/main/scala/bio/ferlab/clin/etl/es/PrepareIndex.scala, src/main/scala/bio/ferlab/clin/etl/fhir/FhirRawToNormalized.scala, src/main/scala/bio/ferlab/clin/etl/utils/FrequencyUtils.scala, src/main/scala/bio/ferlab/clin/etl/varsome/Varsome.scala, src/main/scala/bio/ferlab/clin/etl/vcf/ImportVcf.scala, src/main/scala/bio/ferlab/clin/etl/vcf/Variants.scala, src/test/scala/bio/ferlab/clin/etl/enriched/VariantsSpec.scala, src/test/scala/bio/ferlab/clin/etl/utils/VcfUtilsSpec.scala, src/test/scala/bio/ferlab/clin/model/NormalizedVariants.scala
=> Fixed normalized_variants frequencies

src/main/resources/config/prod.conf, src/main/resources/config/qa.conf, src/main/resources/config/staging.conf, src/main/resources/templates/gene_centric_template.json, src/main/resources/templates/gene_suggestions_template.json, src/main/resources/templates/variant_centric_template.json, src/main/resources/templates/variant_suggestions_template.json, src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala, src/main/scala/bio/ferlab/clin/etl/es/Indexer.scala, src/test/resources/config/test.conf, src/test/scala/bio/ferlab/clin/etl/vcf/VariantsSpec.scala
=> feat: CLIN-928 - review prod

src/main/scala/bio/ferlab/clin/etl/vcf/CNV.scala
=> fix: CLIN-1271 - raw vcf CNV

src/main/scala/bio/ferlab/clin/etl/qc/TestingApp.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/NonDuplicationNorVariants.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/NonDuplicationSNV.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/NonDuplicationVariants.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/SameListBetweenSNVAndNorVariants.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/SameListBetweenSNVAndVariants.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/SameListBetweenVariantsAndVariantCentric.scala
Ajout des datatests de non duplication et de comparaison des variants pour les différentes tables.
=> feat: CLIN-1379 Add variantlist datatests

src/main/resources/templates/gene_centric_template.json
Solution used to perform un-sensitive requests from arranger to ES
Local UI => arranger => ES DONE
Linked to: https://github.com/Ferlab-Ste-Justine/clin-portal-ui/pull/151
=> feat: CLIN-1247 - search genes case sensitive

src/main/scala/bio/ferlab/clin/etl/es/Publish.scala
Retrofit du bug corrigé sur tag v2.3.22
=> fix: CLIN-1427 - publish error

src/main/scala/bio/ferlab/clin/etl/qc/TestingApp.scala, src/main/scala/bio/ferlab/clin/etl/qc/columncontain/ColumnsContainOnlyNullCNV.scala, src/main/scala/bio/ferlab/clin/etl/qc/tables/NonEmptyTables.scala, src/main/scala/bio/ferlab/clin/etl/qc/varsome/VariantsShouldBeAnnotated.scala, src/main/scala/bio/ferlab/clin/etl/qc/varsome/VariantsShouldBeReannotated.scala, src/main/scala/bio/ferlab/clin/etl/qc/varsome/VariantsShouldNotBeAnnotated.scala, src/main/scala/bio/ferlab/clin/etl/qc/varsome/VariantsShouldNotBeReannotated.scala, src/test/scala/bio/ferlab/clin/etl/qc/TestingAppSpec.scala
Ajout de tests pour les tables
- Tables non vides
Ajout de tests pour Varsome
- Les variants annotés
- Les variants non annotés
- Mise-à-jour de l'annotation après 7 jours
- Mise-à-jour de l'annotation pas avant 7 jours
=> feat: CLIN-1379 Add Varsome and non empty tables tests

build.sbt, src/main/resources/config/prod.conf, src/main/resources/config/qa.conf, src/main/resources/config/staging.conf, src/main/scala/bio/ferlab/clin/etl/conf/EtlConfiguration.scala, src/test/resources/config/test.conf
=> feat: CLIN-1555 cleanup + auto merge delta

src/main/scala/bio/ferlab/clin/etl/qc/varsome/VariantsShouldBeReannotated.scala, src/main/scala/bio/ferlab/clin/etl/qc/varsome/VariantsShouldNotBeReannotated.scala
Ajustements aux tests (variants de la dernière batch seulement)
- VariantsShouldBeReannotated
- VariantsShouldNotBeReannotated
=> feat: CLIN-1379 Ajust Varsome tests

src/main/scala/bio/ferlab/clin/etl/qc/TestingApp.scala, src/main/scala/bio/ferlab/clin/etl/qc/tables/NonEmptyTables.scala
Add
- fhir_family
- spliceai_indel
- spliceai_snv
Remove
- cancer_hotspots
=> feat: CLIN-1379 Update table list for NonEmptyTables test

src/main/scala/bio/ferlab/clin/etl/qc/TestingApp.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/ByAnalysisAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/ByAnalysisNonAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/ByAnalysisTotal.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/RQDMAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/RQDMNonAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/RQDMTotal.scala, src/main/scala/bio/ferlab/clin/etl/qc/fromVCF/ContainedInNorVariants.scala, src/main/scala/bio/ferlab/clin/etl/qc/fromVCF/ContainedInSNV.scala
fromVCF
- Table normalized_snv
- Table normalized_variants
frequency
- frequency_RQDM - total
- frequency_RQDM - affected
- frequency_RQDM - non_affected
- frequencies_by_analysis - total
- frequencies_by_analysis - affected
- frequencies_by_analysis - non_affected
=> feat: CLIN-1379 Add fromVCF and frequency DataTest

src/main/scala/bio/ferlab/clin/etl/qc/variantlist/NonDuplicationConsequences.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/NonDuplicationNorConsequences.scala
Add Non duplication Tests
- normalized_consequences
- consequences
=> feat: CLIN-1788 Add Non duplication consequences tests

src/main/scala/bio/ferlab/clin/etl/qc/columncontain/ColumnsContainSameValueVariantCentric.scala, src/main/scala/bio/ferlab/clin/etl/qc/variantlist/NonDuplicationGnomad.scala
Adjustments to DataTests
- CLIN-1756
- CLIN-1785
=> feat: CLIN-1756_CLIN-1785 Adjustments to DataTests

src/main/scala/bio/ferlab/clin/etl/qc/variantlist/NonDuplicationGnomad.scala
Test NonDuplicationGnomad sur gnomad_genomes_v3 au lieu de gnomad_genomes_3_0
=> feat: CLIN-1794 Adjustment to DataTest

src/main/resources/templates/variant_centric_template.json
=> feat: CLIN-1951 - template issue

src/main/scala/bio/ferlab/clin/etl/qc/TestingApp.scala
=> fix: CLIN-1965 Adjustment to DataTest

src/main/scala/bio/ferlab/clin/etl/qc/fromVCF/ContainedInSNV.scala
Ajustement manquant au DataTest vcf_snv
=> feat: CLIN-1994 Adjustment to DataTest

src/main/scala/bio/ferlab/clin/etl/normalized/SNV.scala
Before :
Genotype with low AD was filter out before inheritance and transmissions calcultaions. It cause a lot of null values for these 2 columns
After :
Instead of filtering, we adjust genotypes. If AD is too low, we replace genotype by ./. (-1,-1). Inheritance and transmissions then consider these unknown genotypes instead of null.Rows are then filter out because there is no alternative allele.
=> CLIN-1994 Adjust genotype instead of filtering

src/main/scala/bio/ferlab/clin/etl/enriched/Consequences.scala
=> feat: CLIN-2051 - phylo score

src/main/scala/bio/ferlab/clin/etl/qc/TestingApp.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/Dictionaries.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/DictionariesCNV.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/DictionariesConsequences.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/DictionariesDonors.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/DictionariesSNV.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/package.scala
Add dictionary DataTests
- DictionariesCNV
- DictionariesConsequences
- DictionariesDonors
- DictionariesSNV
L'objectif de ces tests est d'attraper les potentielles nouvelles valeurs en PROD qui ne sont pas incluses dans les dictionnaires harcodés des facettes.
=> feat: CLIN-1379 Add dictionary DataTests

src/main/resources/templates/cnv_centric_template.json, src/main/resources/templates/variant_centric_template.json
Was looking some ES results and found those missing fields in mapping.
=> feat: CLIN-2081 - missing template fields

src/main/scala/bio/ferlab/clin/etl/enriched/Variants.scala, src/test/scala/bio/ferlab/clin/etl/enriched/VariantsSpec.scala
https://ferlab-crsj.atlassian.net/browse/CLIN-2070
=> feat: CLIN-2070 - ignore Somatic/TEBA for pn

src/main/scala/bio/ferlab/clin/etl/qc/dictionary/package.scala
Add SSOLID and SHEMA to panels dictionary
=> feat: CLIN-2125 Adjust dictionary datatests

src/main/scala/bio/ferlab/clin/etl/qc/TestingApp.scala, src/main/scala/bio/ferlab/clin/etl/qc/tables/NonEmptyTables.scala
=> feat: CLIN-2164 Add datatests

src/main/scala/bio/ferlab/clin/etl/qc/columncontain/ColumnsContainOnlyNullVariantCentric.scala, src/main/scala/bio/ferlab/clin/etl/qc/columncontain/ColumnsContainSameValueVariantCentric.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/package.scala
Adjust datatest
- dictionary_snv - CLIN-2201
- add missing tests
=> feat: CLIN-2201 Adjust datatest

src/main/scala/bio/ferlab/clin/etl/qc/dictionary/DictionariesSNV.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/package.scala
Add and adjust DataTest
- CLIN-2206 [Dictionary biotype]
- CLIN-2205 [Dictionary hotspot]
- CLIN-2183 [Dictionary cmc tier]
=> feat: CLIN-2206 Adjust datatest

src/main/scala/bio/ferlab/clin/etl/qc/frequency/ByAnalysisAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/ByAnalysisNonAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/ByAnalysisTotal.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/RQDMAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/RQDMNonAffected.scala, src/main/scala/bio/ferlab/clin/etl/qc/frequency/RQDMTotal.scala
[CLIN-2470](https://ferlab-crsj.atlassian.net/browse/CLIN-2470) [DataTest] Corriger les tests freq_*
=> feat: CLIN-2470 Adjust datatests

src/test/scala/bio/ferlab/clin/etl/enriched/VariantsSpec.scala
In case we change the code later, the unit test will crash.
=> feat: CLIN-2550 insure family_id isnt grouped by

src/main/scala/bio/ferlab/clin/etl/qc/dictionary/DictionariesDonors.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/DictionariesSNV.scala, src/main/scala/bio/ferlab/clin/etl/qc/dictionary/package.scala
Add Exomiser and Franklin dictionaries Datatests
=> feat: CLIN-2500 Add datatests

src/main/resources/templates/variant_centric_template.json, src/main/scala/bio/ferlab/clin/etl/enriched/Variants.scala, src/main/scala/bio/ferlab/clin/etl/utils/FrequencyUtils.scala, src/test/scala/bio/ferlab/clin/etl/enriched/VariantsSpec.scala, src/test/scala/bio/ferlab/clin/model/VariantIndexOutput.scala, src/test/scala/bio/ferlab/clin/model/enriched/EnrichedVariant.scala
TODO: Confirm somaticTumorNormalFrequencyFilter with geneticians
=> feat: CLIN-2938 Compute somatic frequencies

src/main/scala/bio/ferlab/clin/etl/qc/dictionary/package.scala
- closes #CLIN-2969
[CLIN-2969](https://ferlab-crsj.atlassian.net/browse/CLIN-2969)
[CLIN-2969]: https://ferlab-crsj.atlassian.net/browse/CLIN-2969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: CLIN-2969 Add THBP panel to DataTests
